---
title: "PCA with Amino Acids in R"
output: html_notebook
---

```{r}
library(vegan)
library(MASS)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(ggfortify)
```
```{r}
# path1 <- 'C:/Users/jschiff.GEOSAD/Google Drive/projects/rproj/seus/data/schiff c-csiaa stetson.csv'
# path <- '~/Documents/GitHub/data/schiff c-csiaa data from schiff_larsen_in prog.csv'
path <- '~/Documents/GitHub/data/schiff c-csiaa_training dataset.csv'
carbon <- read.csv(path) # Check original excel sheet for standard deviations, etc. 

carbon %>%
  dplyr::select(Group.ID, Group.ID2, Category, Source, Phe, Thr, Ile, Leu, Val) %>%
  filter(Category == "Microalgae" |
           Category == "Macroalgae" |
           Category == "Bacteria" |
           Category == "Sediment trap" |
           Category == 'Cyanobacteria' |
           # Feature == "Seagrasses" |
           Category == "Leiopathes"
           # Feature == 'Leiopathes'
         ) -> pca_set

pca_set <- droplevels(pca_set)
pca_set <- na.omit(pca_set)
pca_set2 <- pca_set[,c(5:9)] - rowMeans(pca_set[,c(5:9)])
t.pca <- rda(pca_set2, scale = TRUE)
df_pca <- prcomp(pca_set2, center = TRUE, scale. = TRUE)
summary(eigenvals(t.pca)) # Important for getting variance in vegan objects
```
```{r}
# Plotting
par(pty = "s")
biplot(t.pca,
       display = c("species"),
       type = c("text"),
       col = c("#252525", "black"),
       xlab = "PC1",
       ylab = "PC2",
       xlim = c(-2,2),
       ylim = c(-2,2))
points(t.pca,
       pch = c(21,22,22,23,23,24,22)[as.numeric(pca_set$Category)],
       cex = 1.25,
       col = "black",

bg = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")[as.numeric(pca_set$Category)])
legend("topright",
       lty = NULL,
       bty = "n",
       pch = c(21,22,22,23,23,24,22),
       legend = levels(pca_set$Category),
       cex = 0.75,
       inset=c(-0.1,0),
       pt.cex = 0.95,
       pt.bg = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"))
```

```{r}
# PCA with ggplot2 visualization
# Note, biplot is built in to be used for vegan, so it is better to use the standard
# R functions for pca

# Method 1
# carbon %>%
#   dplyr::select(Category, Phe, Thr, Ile, Leu, Val) %>%
#   filter(Category == "Microalgae" |
#            Category == "Macroalgae" |
#            Category == "Bacteria" |
#            # Category == "Sediment trap" |
#            Category == 'Cyanobacteria'
#            # Feature == "Seagrasses" |
#            # Category == "Leiopathes-pre" |
#            # Category == "Leiopathes-post"
#            # Feature == 'Leiopathes'
#          ) -> endmembers
# 
# carbon %>%
#   dplyr::select(Category, Phe, Thr, Ile, Leu, Val) %>%
#   filter(Category == "Leiopathes-pre" |
#            Category == "Leiopathes-post") -> test_data

# Method 2
carbon %>%
  dplyr::select(Group.ID2, Phe, Thr, Ile, Leu, Val) %>%
  filter(Group.ID2 == "Microalgae" |
           Group.ID2 == "Macroalgae" |
           Group.ID2 == "Bacteria" |
           # Category == "Sediment trap" |
           Group.ID2 == 'Leiopathes'
         ) -> endmembers

# carbon %>%
#   dplyr::select(Group.ID2, Phe, Thr, Ile, Leu, Val) %>%
#   filter(Group.ID2 == "Leiopathes) -> test_data

head(endmembers)
row.names(endmembers) <- paste(endmembers$Group.ID2, row.names(endmembers), sep="_") 
head(endmembers)
endmembers$Group.ID2 <- NULL
head(endmembers)
df_pca <- prcomp(endmembers, scale = TRUE)
df_pca
```

```{r}
# 
# # Using ggplot
# # plot(df_pca$x[,1], df_pca$x[,2])
# df_out <- as.data.frame(df_pca$x)
# df_out$group <- sapply(strsplit(as.character(row.names(endmembers)), "_"), "[[", 1)
# head(df_out)
# 
# # p <- ggplot(df_out,aes(x=PC1,y=PC2,color=group ))
# # p <- p + geom_point()
# # p
# percentage <- round(df_pca$sdev / sum(df_pca$sdev) * 100, 0)
# percentage <- paste( colnames(df_out), "(", paste( as.character(percentage), "%", ")", sep="") )
# 
# theme <- theme(panel.background = element_blank(),
#                panel.border=element_rect(fill=NA),
#                panel.grid.major = element_blank(),
#                panel.grid.minor = element_blank(),
#                strip.background=element_blank(),
#                axis.text.x=element_text(colour="black"),
#                axis.text.y=element_text(colour="black"),
#                axis.ticks=element_line(colour="black"),
#                plot.margin=unit(c(1,1,1,1),"line"))
# 
# p <- ggplot(df_out,aes(x=PC1,y=PC2,color=group ))
# p <- p + geom_point() + theme + xlab(percentage[1]) + ylab(percentage[2])
# p
```


```{r}
# Using ggfortify
carbon %>%
  dplyr::select(Group.ID2, Phe, Thr, Ile, Leu, Val) %>%
  filter(Group.ID2 == "Microalgae" |
           Group.ID2 == "Macroalgae" |
           Group.ID2 == "Bacteria" |
           Group.ID2 == "Plants" |
           # Group.ID2 == 'Seagrasses' |
           Group.ID2 == 'Leiopathes'
         ) -> endmembers

# carbon %>%
#   dplyr::select(Category, Phe, Thr, Ile, Leu, Val) %>%
#   filter(
#     Category == "Bacteria" |
#       Category == "Cyanobacteria" |
#             Category == "Cyanobacteria-L" |
#       Category == "Diatom" |
#       Category == "Phaeophyte" | # Brown algae
#       Category == 'Haptophyte' | # Coccolithophore
#       Category == 'Leiopathes'
#   ) -> endmembers
mydata <- endmembers
mydata <- na.omit(mydata)
mydata_labels <- mydata
head(mydata)
row.names(mydata) <- paste(mydata$Group.ID2, row.names(mydata), sep="_") # Change between Category or Group.ID2
head(mydata)
mydata$Group.ID2 <- NULL
head(mydata)
mydata <- mydata - rowMeans(mydata)
df_pca <- prcomp(mydata, scale. = TRUE)
# df_pca <- princomp(mydata, cor = TRUE, scores = TRUE)
#
df_out <- as.data.frame(df_pca$x)
# df_out <- as.data.frame(df_pca$scores)
df_out$group <- sapply(strsplit(as.character(row.names(mydata)), "_"), "[[", 1)
head(df_out)

theme <- theme(panel.background = element_blank(),
               panel.border=element_rect(fill=NA),
               panel.grid.major = element_blank(),
               panel.grid.minor = element_blank(),
               strip.background=element_blank(),
               axis.text.x=element_text(colour="black"),
               axis.text.y=element_text(colour="black"),
               axis.ticks=element_line(colour="black"),
               plot.margin=unit(c(1,1,1,1),"line"))

p <- autoplot(df_pca, data = mydata_labels, fill = 'Group.ID2', color = 'black', shape = 'Group.ID2', size = 3, loadings = TRUE, loadings.colour = 'black',
              frame = FALSE, frame.type = 'norm', scale = 0)
p <- p + theme
p <- p + scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")) + scale_shape_manual(values=c(21:22, 8, 23:25))
p <- p + labs(fill = "Group") + labs(shape = "Group")
p

ggsave('~/Desktop/pca_.pdf', plot=last_plot(), width = 7, height = 5, dpi = 300)
```

```{r}
# Linear discriminant analysis
carbon %>%
  dplyr::select(Group.ID2, Phe, Thr, Ile, Leu, Val) %>%
  filter(
    Group.ID2 == "Microalgae" |
      Group.ID2 == "Macroalgae" |
      Group.ID2 == "Bacteria" 
      # Group.ID2 == "Plants"
      # Group.ID2 == 'Leiopathes'
         ) -> endmembers
head(endmembers)
carbon %>%
  dplyr::select(Group.ID2, Phe, Thr, Ile, Leu, Val) %>%
  filter(Group.ID2 == "Leiopathes") -> leio

carbon %>%
  dplyr::select(Group.ID2, Phe, Thr, Ile, Leu, Val) %>%
  filter(Group.ID2 == "Sediment trap") -> sediment

carbon %>%
  dplyr::select(Group.ID2, Phe, Thr, Ile, Leu, Val) %>%
  filter(Group.ID2 == "Isidella A7") -> isidella

train <- endmembers
train <- na.omit(train)
train <- droplevels(train)
leio <- droplevels(leio)
sediment <- droplevels(sediment)
isidella <- droplevels(isidella)

lda_train <- lda(Group.ID2 ~ Phe + Thr + Ile + Leu, train)
pred <- predict(lda_train, newdata = leio) # pred$x has 10 items because there were ten (10) d13CAA samples
pred_sediment <- predict(lda_train, newdata = sediment)
pred_isidella <- predict(lda_train, newdata = isidella)

lda_data <- cbind(train, predict(lda_train)$x)
leio_data <- cbind(leio, pred$x)
sediment_data <- cbind(sediment, pred_sediment$x)
isidella_data <- cbind(isidella, pred_isidella$x)
lda_data <- rbind(lda_data, leio_data, sediment_data, isidella_data)

p1 <- ggplot(lda_data, aes(LD1, LD2)) + geom_point(aes(shape = Group.ID2, fill = Group.ID2), size = 3)
p1 <- p1 + theme_linedraw() + theme(panel.grid = element_blank())
p1 <- p1 + scale_shape_manual(values=c(21:25))
p1 <- p1 + scale_fill_manual(values=c('#d7191c','#fdae61','#ffffbf','#abd9e9','#2c7bb6'))
p1

```


```{r}

pred.train <- predict(lda_train,train)$class
pred.test <- predict(lda_train,leio)$class
mean(pred.train == train$Group.ID2)
mean(pred.test == train$Group.ID2)


lda.test <- predict(lda_train, train)
train$lda <- lda.test$class
table(train$lda, train$Group.ID2)


lda.test <- predict(lda_train,leio)
leio$lda <- lda.test$class
table(leio$lda,leio$Group.ID2)
```

```{r}
# Linear discriminant analysis
carbon %>%
  dplyr::select(Category, Phe, Thr, Ile, Leu, Val) %>%
  filter(
    Category == "Bacteria" |
      Category == "Cyanobacteria" |
      Category == "Eukaryotic phytoplankton" |
      Category == "Brown algae" |
      Category == "Green algae"
         ) -> endmembers
head(endmembers)
carbon %>%
  dplyr::select(Category, Phe, Thr, Ile, Leu, Val) %>%
  filter(Category == "Leiopathes") -> leio

carbon %>%
  dplyr::select(Category, Phe, Thr, Ile, Leu, Val) %>%
  filter(Category == "Sediment trap") -> sediment

carbon %>%
  dplyr::select(Category, Phe, Thr, Ile, Leu, Val) %>%
  filter(Category == "Isidella") -> isidella

train <- endmembers
train <- na.omit(train)
train <- droplevels(train)
leio <- droplevels(leio)
sediment <- droplevels(sediment)
isidella <- droplevels(isidella)

lda_train <- lda(Category ~ Phe + Thr + Ile + Leu, train)
pred <- predict(lda_train, newdata = leio) # pred$x has 10 items because there were ten (10) d13CAA samples
# pred_sediment <- predict(lda_train, newdata = sediment)
# pred_isidella <- predict(lda_train, newdata = isidella)

lda_data <- cbind(train, predict(lda_train)$x)
leio_data <- cbind(leio, pred$x)
# sediment_data <- cbind(sediment, pred_sediment$x)
# isidella_data <- cbind(isidella, pred_isidella$x)
# lda_data <- rbind(lda_data, leio_data, sediment_data, isidella_data)
lda_data <- rbind(lda_data, leio_data)

p1 <- ggplot(lda_data, aes(LD1, LD2)) + geom_point(aes(shape = Category, fill = Category), size = 3)
p1 <- p1 + theme_linedraw() + theme(panel.grid = element_blank(), axis.ticks.x = element_line(size = 0.25, color = "black"))
p1 <- p1 + scale_shape_manual(values=c(21:25))
p1 <- p1 + scale_fill_manual(values=c('#d7191c','#fdae61','#ffffbf','#abd9e9','#2c7bb6'))
p1

ggsave('~/Desktop/lda_1.png', plot=last_plot(), width = 7, height = 5, dpi = 300)
```

```{r}
pred.train <- predict(lda_train,train)$class
pred.test <- predict(lda_train,leio)$class
mean(pred.train == train$Category)
# mean(pred.test == train$Category)


lda.test <- predict(lda_train, train)
train$lda <- lda.test$class
table(train$lda, train$Category)


lda.test <- predict(lda_train,leio)
leio$lda <- lda.test$class
table(leio$lda,leio$Category)
```

```{r}
carbon %>%
  dplyr::select(Category, Phe, Thr, Ile, Leu, Val) %>%
  filter(Category == "Bacteria" |
      Category == "Cyanobacteria" |
      Category == "Eukaryotic phytoplankton" |
      Category == "Brown algae" |
      Category == "Green algae"
    # Category == "Bacteria" |
    #   Category == "Cyanobacteria" |
    #   Category == "Diatom" |
    #   Category == "Leiopathes" |
    #   Category == "Phaeophyte" | # Brown algae
    #   Category == 'Haptophyte' # Coccolithophore
         ) -> endmembers

mydata <- endmembers
mydata <- na.omit(mydata)
mydata_labels <- mydata
head(mydata)
row.names(mydata) <- paste(mydata$Category, row.names(mydata), sep="_") # Change between Category or Group.ID2
head(mydata)
mydata$Category <- NULL
head(mydata)
mydata <- mydata - rowMeans(mydata)
df_pca <- prcomp(mydata, scale. = TRUE)
# df_pca <- princomp(mydata, cor = TRUE, scores = TRUE)
#
df_out <- as.data.frame(df_pca$x)
# df_out <- as.data.frame(df_pca$scores)
df_out$group <- sapply(strsplit(as.character(row.names(mydata)), "_"), "[[", 1)
head(df_out)

# theme <- theme(panel.background = element_blank(),
#                panel.border=element_rect(fill=NA),
#                panel.grid.major = element_blank(),
#                panel.grid.minor = element_blank(),
#                strip.background=element_blank(),
#                axis.text.x=element_text(colour="black"),
#                axis.text.y=element_text(colour="black"),
#                axis.ticks=element_line(colour="black"),
#                plot.margin=unit(c(1,1,1,1),"line"))

p <- autoplot(df_pca, data = mydata_labels, fill = 'Category', color = 'black', shape = 'Category', size = 3, loadings = TRUE, loadings.colour = 'black',
              frame = FALSE, frame.type = 'norm', scale = 0)
p <- p + theme_linedraw() + theme(panel.grid = element_blank(), axis.ticks.x = element_line(size = 0.25, color = "black"))
p <- p + scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")) + scale_shape_manual(values=c(21:22,23,24,8,25))
p <- p + labs(fill = "Group") + labs(shape = "Group")
p

ggsave('~/Desktop/pca_2.pdf', plot=last_plot(), width = 7, height = 5, dpi = 300)
```

